/**
 * Cloudflare Worker entry point — auto-generated by vinext deploy.
 * Edit freely or delete to regenerate on next deploy.
 *
 * For apps without image optimization, you can use vinext/server/app-router-entry
 * directly in wrangler.jsonc: "main": "vinext/server/app-router-entry"
 */
import { handleImageOptimization, DEFAULT_DEVICE_SIZES, DEFAULT_IMAGE_SIZES } from "vinext/server/image-optimization";
import type { ImageConfig } from "vinext/server/image-optimization";
import handler from "vinext/server/app-router-entry";

interface Env {
  ASSETS: Fetcher;
  DB: any;
  AWS_ACCESS_KEY_ID?: string;
  AWS_SECRET_ACCESS_KEY?: string;
  AWS_REGION?: string;
  AWS_S3_BUCKET?: string;
  AWS_S3_ENDPOINT?: string;
  AWS_S3_PUBLIC_BASE_URL?: string;
  OPENAI_API_KEY?: string;
  OPENAI_BASE_URL?: string;
  OPENAI_MODEL?: string;
  IMAGES: {
    input(stream: ReadableStream): {
      transform(options: Record<string, unknown>): {
        output(options: { format: string; quality: number }): Promise<{ response(): Response }>;
      };
    };
  };
}

interface ExecutionContext {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
}

// Image security config. SVG sources with .svg extension auto-skip the
// optimization endpoint on the client side (served directly, no proxy).
// To route SVGs through the optimizer (with security headers), set
// dangerouslyAllowSVG: true in next.config.js and uncomment below:
// const imageConfig: ImageConfig = { dangerouslyAllowSVG: true };

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);

    // Expose bindings to app route handlers running in edge runtime.
    // Route handlers can read globalThis.DB during the request lifecycle.
    (globalThis as any).__RUNTIME_ENV = env;
    (globalThis as any).DB = env.DB;
    (globalThis as any).AWS_ACCESS_KEY_ID = env.AWS_ACCESS_KEY_ID;
    (globalThis as any).AWS_SECRET_ACCESS_KEY = env.AWS_SECRET_ACCESS_KEY;
    (globalThis as any).AWS_REGION = env.AWS_REGION;
    (globalThis as any).AWS_S3_BUCKET = env.AWS_S3_BUCKET;
    (globalThis as any).AWS_S3_ENDPOINT = env.AWS_S3_ENDPOINT;
    (globalThis as any).AWS_S3_PUBLIC_BASE_URL = env.AWS_S3_PUBLIC_BASE_URL;
    (globalThis as any).OPENAI_API_KEY = env.OPENAI_API_KEY;
    (globalThis as any).OPENAI_BASE_URL = env.OPENAI_BASE_URL;
    (globalThis as any).OPENAI_MODEL = env.OPENAI_MODEL;

    // Image optimization via Cloudflare Images binding.
    // The parseImageParams validation inside handleImageOptimization
    // normalizes backslashes and validates the origin hasn't changed.
    if (url.pathname === "/_vinext/image") {
      const allowedWidths = [...DEFAULT_DEVICE_SIZES, ...DEFAULT_IMAGE_SIZES];
      return handleImageOptimization(request, {
        fetchAsset: (path) => env.ASSETS.fetch(new Request(new URL(path, request.url))),
        transformImage: async (body, { width, format, quality }) => {
          const result = await env.IMAGES.input(body).transform(width > 0 ? { width } : {}).output({ format, quality });
          return result.response();
        },
      }, allowedWidths);
    }

    // Delegate everything else to vinext, forwarding ctx so that
    // ctx.waitUntil() is available to background cache writes and
    // other deferred work via getRequestExecutionContext().
    return handler.fetch(request, env, ctx);
  },
};
